# Generated by Django 5.1.7 on 2025-03-27 08:23

import django.db.models.deletion
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время окончания')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Название слота на сайте')),
                ('is_available_tomorrow', models.BooleanField(default=True, verbose_name='Доступен для доставки на завтра')),
                ('is_express', models.BooleanField(default=False, verbose_name='"Как можно скорее"')),
            ],
            options={
                'verbose_name': 'Слот доставки',
                'verbose_name_plural': 'Слоты доставки',
                'ordering': ['time_start'],
            },
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Минимальная цена')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Максимальная цена')),
            ],
            options={
                'verbose_name': 'Ценовой диапазон',
                'verbose_name_plural': 'Ценовые диапазоны',
            },
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True, verbose_name='ID Телеграма')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Телефон', max_length=31)),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('owner', 'Владелец сервиса'), ('user', 'Пользователь'), ('admin', 'Админ'), ('manager', 'Менеджер'), ('delivery', 'Доставщик')], default='user', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('composition', models.TextField(verbose_name='Состав букета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='img/catalog/', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('active', 'Актуальный'), ('archived', 'Архивный')], default='active', max_length=10, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('categories', models.ManyToManyField(to='flowershopservice.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название букета')),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена букета')),
                ('product_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение букета')),
                ('product_composition', models.TextField(blank=True, null=True, verbose_name='Состав букета')),
                ('comment', models.TextField(blank=True, max_length=300, null=True, verbose_name='Комментарий к заказу')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(null=True, verbose_name='Дата доставки')),
                ('is_express_delivery', models.BooleanField(default=False, verbose_name='Экспресс-доставка')),
                ('delivery_time_from', models.TimeField(blank=True, null=True, verbose_name='Доставка с')),
                ('delivery_time_to', models.TimeField(blank=True, null=True, verbose_name='Доставка до')),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время доставки')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('inWork', 'В работе'), ('inDelivery', 'В доставке'), ('delivered', 'Выдан клиенту'), ('cancelled', 'Отменен')], default='created', max_length=12, verbose_name='Статус заказа')),
                ('delivery_comments', models.TextField(blank=True, null=True, verbose_name='Комментарии к доставке')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowershopservice.product', verbose_name='Букет')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='flowershopservice.shopuser', verbose_name='Доставщик')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_orders', to='flowershopservice.shopuser', verbose_name='Менеджер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='flowershopservice.shopuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed', models.BooleanField(default=False, verbose_name='Статус заявки')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_consultations', to='flowershopservice.shopuser', verbose_name='Менеджер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='flowershopservice.shopuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
        migrations.CreateModel(
            name='DeliveryManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_date', models.DateField(verbose_name='Рабочий день')),
                ('shift_start', models.TimeField(verbose_name='Начало смены')),
                ('shift_end', models.TimeField(verbose_name='Конец смены')),
                ('max_orders_per_day', models.PositiveIntegerField(default=10, verbose_name='Максимум заказов в день')),
                ('current_orders_count', models.PositiveIntegerField(default=0, verbose_name='Текущее количество заказов')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для назначения')),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedule', to='flowershopservice.shopuser', verbose_name='Доставщик')),
            ],
            options={
                'verbose_name': 'График доставщика',
                'verbose_name_plural': 'Графики доставщиков',
                'unique_together': {('delivery_person', 'working_date')},
            },
        ),
    ]
