# Generated by Django 5.1.7 on 2025-03-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowershopservice", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverytimeslot",
            options={
                "ordering": ["time_start"],
                "verbose_name": "Слот доставки",
                "verbose_name_plural": "Слоты доставки",
            },
        ),
        migrations.RemoveField(
            model_name="deliverytimeslot",
            name="current_deliveries",
        ),
        migrations.RemoveField(
            model_name="deliverytimeslot",
            name="date",
        ),
        migrations.RemoveField(
            model_name="deliverytimeslot",
            name="max_deliveries",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_time_slot",
        ),
        migrations.AddField(
            model_name="deliverytimeslot",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Название слота на сайте"
            ),
        ),
        migrations.AddField(
            model_name="deliverytimeslot",
            name="is_available_tomorrow",
            field=models.BooleanField(
                default=True, verbose_name="Доступен для доставки на завтра"
            ),
        ),
        migrations.AddField(
            model_name="deliverytimeslot",
            name="is_express",
            field=models.BooleanField(default=False, verbose_name='"Как можно скорее"'),
        ),
        migrations.AddField(
            model_name="order",
            name="actual_delivery_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Фактическое время доставки"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(null=True, verbose_name="Дата доставки"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_time_from",
            field=models.TimeField(blank=True, null=True, verbose_name="Доставка с"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_time_to",
            field=models.TimeField(blank=True, null=True, verbose_name="Доставка до"),
        ),
        migrations.AddField(
            model_name="order",
            name="is_express_delivery",
            field=models.BooleanField(
                default=False, verbose_name="Доставка как можно скорее"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product_composition",
            field=models.TextField(blank=True, null=True, verbose_name="Состав букета"),
        ),
        migrations.AddField(
            model_name="order",
            name="product_image",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Изображение букета"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product_name",
            field=models.CharField(
                default=0.0, max_length=200, verbose_name="Название букета"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="product_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Цена букета"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flowershopservice.product",
                verbose_name="Букет",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="img/catalog/", verbose_name="Изображение"
            ),
        ),
        migrations.CreateModel(
            name="DeliveryManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("working_date", models.DateField(verbose_name="Рабочий день")),
                ("shift_start", models.TimeField(verbose_name="Начало смены")),
                ("shift_end", models.TimeField(verbose_name="Конец смены")),
                (
                    "max_orders_per_day",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Максимум заказов в день"
                    ),
                ),
                (
                    "current_orders_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Текущее количество заказов"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Доступен для назначения"
                    ),
                ),
                (
                    "delivery_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_schedule",
                        to="flowershopservice.shopuser",
                        verbose_name="Доставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "График доставщика",
                "verbose_name_plural": "Графики доставщиков",
                "unique_together": {("delivery_person", "working_date")},
            },
        ),
    ]
