# Generated by Django 5.1.7 on 2025-03-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershopservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID'),
        ),
    ]
