# Generated by Django 5.1.7 on 2025-03-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowershopservice', '0002_shopuser_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='user_id',
        ),
    ]
