# Generated by Django 5.1.7 on 2025-03-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershopservice', '0002_alter_shopuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('coord_x', models.FloatField(verbose_name='Координата X')),
                ('coord_y', models.FloatField(verbose_name='Координата Y')),
                ('image', models.ImageField(upload_to='shops/', verbose_name='Фото салона')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('working_hours', models.CharField(default='10:00-20:00', max_length=100, verbose_name='Часы работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['order'],
            },
        ),
    ]
