# Generated by Django 5.1.7 on 2025-03-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershopservice', '0003_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='last_address',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='coord_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Координата X (широта)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='coord_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Координата Y (долгота)'),
        ),
    ]
