# Generated by Django 5.1.7 on 2025-03-29 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershopservice', '0004_shop_last_address_alter_shop_coord_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. От 9 до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
