# Generated by Django 5.1.7 on 2025-03-30 07:40

import django.core.validators
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershopservice', '0005_alter_shopuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ФИО может содержать только буквы, цифры и пробелы', regex='^[a-zA-Zа-яА-Я0-9\\s]+$')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Телефон', max_length=31, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +7XXXXXXXXXX', regex='^\\+7\\d{10}$')]),
        ),
    ]
