# Generated by Django 5.1.7 on 2025-03-30 11:47

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershopservice', '0007_alter_shopuser_full_name_alter_shopuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Телефон', max_length=31, unique=True),
        ),
    ]
